---
- name: 워커 노드에 Docker 서비스 배포
  hosts: workers  # 인벤토리에 정의된 워커 노드 그룹
  become: yes     # sudo 권한 사용
  vars:
    project_dir: /home/user1/  # 워커 노드에서 프로젝트가 위치할 경로
    
  tasks:
    - name: 프로젝트 디렉토리 생성
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'
      
    - name: docker-compose.yml 파일 복사
      copy:
        src: ./docker-compose.yml  # 매니저 PC의 플레이북 위치 기준 상대 경로
        dest: "{{ project_dir }}/docker-compose.yml"
        mode: '0644'
        
    - name: requirements.txt 파일 복사
      copy:
        src: ./requirements.txt
        dest: "{{ project_dir }}/requirements.txt"
        mode: '0644'
        
    - name: producer.py 파일 복사
      copy:
        src: ./producer.py  # 미확인 336947.crdownload 파일의 내용을 producer.py로 저장해야 함
        dest: "{{ project_dir }}/weather-producer/producer.py"
        mode: '0644'
      
    - name: Dockerfile 복사
      copy:
        src: ./Dockerfile
        dest: "{{ project_dir }}/weather-producer/Dockerfile"
        mode: '0644'
        
    - name: Logstash 설정 파일 복사
      copy:
        src: ./final.conf
        dest: "{{ project_dir }}/logstash/conf.d/final.conf"
        mode: '0644'
        
    - name: 필요한 디렉토리 생성 (Zookeeper용)
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ project_dir }}/../zookeeper/data/1"
        - "{{ project_dir }}/../zookeeper/data/2"
        - "{{ project_dir }}/../zookeeper/datalog/1"
        - "{{ project_dir }}/../zookeeper/datalog/2"
        - "{{ project_dir }}/../zookeeper/logs/1"
        - "{{ project_dir }}/../zookeeper/logs/2"
        
    - name: 필요한 디렉토리 생성 (Kafka용)
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ project_dir }}/../kafka/logs/1"
        - "{{ project_dir }}/../kafka/logs/2"
        
    - name: Docker Compose 실행
      shell: docker-compose up -d
      args:
        chdir: "{{ project_dir }}"
