---
- hosts: web1
  become: yes
  tasks:
    - name: Ping the server
      ansible.builtin.ping:

    - name: Pull latest code from worker branch
      git:
        repo: 'https://github.com/2guno/toy_project.git'
        dest: /home/user1
        version: worker
        force: yes

    - name: Run docker-compose up
      shell: docker-compose up -d
      args:
        chdir: /home/ubuntu/worker_dir
