---
- name: Ping all hosts
  hosts: all
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: show ip server
      debug:
        msg: "Host IP is {{ ansible_default_ipv4.address }}"

    - name: show pwd
      shell: pwd
      register: current_dir

    - name: Print working directory
      debug:
        msg: "Current working directory is {{ current_dir.stdout }}"

    - name: Run docker-compose up
      shell: docker-compose up -d
      args:
        chdir: /home/user1
