server.host: "0.0.0.0"
server.name: kibana
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: elastic
elasticsearch.password: test123
xpack.maps.enabled: true
xpack.maps.showMapVisualizationTypes: true
map.includeElasticMapsService: true
